<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Giới thiệu - Quản lý bản quyền tác giả | Nhà Sách Trí Tuệ</title>
  <link rel="stylesheet" href="../css/gioithieu.css">
</head>
<body>
    <%@ include file="../WebNguoiDung/CTDheader.jsp" %>
   <main>
    <section class="intro">
      <div class="text-box">
        <h1>Giới thiệu hoạt động Cục Bản quyền tác giả</h1>
        <p>Ngày 20 tháng 2 năm 1987, Hãng bảo hộ Quyền tác giả Việt Nam, tiền thân của Cục Bản quyền tác giả, được thành lập. Trong bối cảnh đất nước bước vào thực hiện công cuộc đổi mới, những người chuẩn bị và đưa ra quyết định thành lập Hãng bảo hộ Quyền tác giả đã thấy được vai trò của quyền sở hữu trí tuệ trong công cuộc xây dựng và phát triển kinh tế – văn hóa – xã hội của Việt Nam. Đây là lựa chọn đúng đắn để hướng tới văn minh nhân loại. Sự ra đời của Cục Bản quyền tác giả gắn liền với chính sách phát triển sở hữu trí tuệ Việt Nam, vì vậy những thành tựu của sự nghiệp bảo hộ quyền sở hữu trí tuệ dưới sự lãnh đạo của Đảng, quản lý của Nhà nước trong 25 năm qua có sự đồng hành của cơ quan quản lý là Cục Bản quyền tác giả, Bộ Văn hóa, Thể thao và Du lịch.</p>
        <p>Hai mươi lăm năm là khoảng thời gian chưa dài của một tổ chức, nhưng là một chặng đường không ngắn để đặt dấu ấn vào lịch sử công tác bảo hộ quyền tác giả ở Việt Nam. Trải qua hai mươi lăm năm xây dựng và trưởng thành, Cục Bản quyền tác giả đã có những đóng góp không nhỏ vào những thành tựu đạt được trong công tác bảo hộ quyền sở hữu trí tuệ, trong đó có quyền tác giả, quyền liên quan của đất nước.</p>
        <p>Hệ thống pháp luật được hình thành, điều chỉnh hầu hết các quan hệ xã hội liên quan đến hoạt động sáng tạo, bảo hộ quyền đối với tài sản do công dân tạo ra.</p>
        <p>Cục Bản quyền tác giả đã chủ trì và phối hợp với các tổ chức, cơ quan tổ chức nghiên cứu, xây dựng và trình các cấp có thẩm quyền ban hành trên 30 loại văn bản quy phạm pháp luật, với tổng số trên 620 điều luật. Đây là khối lượng công việc đã được ghi nhận tại các văn bản pháp luật từ các quy định tại Hiến pháp, Bộ luật Dân sự, Luật Hành chính, Bộ luật Hình sự, Luật Sở hữu trí tuệ, các luật chuyên ngành báo chí, xuất bản, điện ảnh, di sản, quảng cáo, hải quan cùng các Chỉ thị, Nghị định và các Thông tư. Khối lượng các điều khoản về quyền tác giả, quyền liên quan chứa đựng các nội dung rất mới mẻ, chưa có tiền lệ và đặc biệt phức tạp.</p>
        <p>Các văn bản pháp luật nêu trên được ban hành và sửa đổi phù hợp với tình hình mới, đủ sức để bảo hộ thành quả của lao động sáng tạo tại quốc gia và hội nhập quốc tế, vì vậy đã góp phần quan trọng khẳng định chính sách sở hữu trí tuệ của Việt Nam và nâng cao vị thế của Việt Nam trên trường quốc tế. Hiện tại có 226 Điều luật đang có hiệu lực thi hành trên phạm vi cả nước. Các công việc lập pháp nêu trên là thành quả của quá trình thể chế hóa hiến pháp qua các thời kỳ.</p>
        <p>Tham gia 8 Điều ước quốc tế song phương và đa phương về quyền tác giả, quyền liên quan, đưa Việt Nam hội nhập sâu rộng vào cộng đồng quốc tế:</p>
        <p>Năm Công ước và Hiệp ước quốc tế gồm: Berne, Rome, Geneva, TRIPs, Brussel bảo hộ tác phẩm văn học nghệ thuật, khoa học và các cuộc biểu diễn, bản ghi âm, chương trình máy tính, tín hiệu vệ tinh mang chương trình được mã hóa, đã lần lượt có hiệu lực tại Việt Nam. Trong đó Công ước Berne có hiệu lực trước tiên vào ngày 26/4/2004, Hiệp định TRIPs về các khía cạnh thương mại của quyền sở hữu trí tuệ có hiệu lực ngày 11 tháng 01 năm 2007 đồng thời với thời điểm Việt Nam là thành viên của WTO.</p>
        <p>Ba điều ước quốc tế song phương gồm Hiệp định thiết lập quan hệ quyền tác giả và Hiệp định thương mại với Hoa Kỳ, Hiệp định bảo hộ quyền sở hữu trí tuệ với Liên bang Thụy Sĩ cũng đã lần lượt có hiệu lực tại các quốc gia ký kết. Ngoài ra, tại các Hiệp định đa phương và song phương về kinh tế, thương mại, đầu tư, dịch vụ v.v… mà Việt Nam đã ký kết, tham gia cũng bao gồm các cam kết về bảo hộ quyền sở hữu trí tuệ, trong đó có quyền tác giả, quyền liên quan như Hiệp định đối tác kinh tế Việt Nam – Nhật Bản hoặc Hiệp định đối tác kinh tế xuyên Thái Bình Dương mà Việt Nam đang tham gia đàm phán cùng 8 quốc gia khác.</p>
        <p>Các Điều ước và Hiệp ước quốc tế, Hiệp định nêu trên có khoảng trên 200 điều luật, là những quy định về quyền và nghĩa vụ của các bên. Công dân và pháp nhân các quốc gia thành viên phải có nghĩa vụ khi khai thác các quyền tác giả, quyền liên quan của công dân và pháp nhân Việt Nam, ngược lại công dân và pháp nhân Việt Nam phải thực hiện nghĩa vụ pháp lý khi khai thác, sử dụng quyền tác giả, quyền liên quan của công dân và pháp nhân của các quốc gia thành viên liên quan.</p>
        <p>Các Công ước và Hiệp ước quốc tế nêu trên đã và đang tác động sâu sắc đến toàn bộ đời sống văn học, nghệ thuật của Việt Nam, với những diễn biến tích cực và cả những hạn chế.</p>
        <p>Hoạt động tuyên truyền, giáo dục pháp luật được triển khai với nhiều hình thức phong phú, đa dạng đã góp phần nâng cao nhận thức tư tưởng, hiểu biết về quyền tác giả, quyền liên quan.</p>
        <p>Có tổng số 50 Cuốn sách đã được xuất bản với các nội dung là văn bản pháp luật quốc gia và quốc tế. Các sách nghiên cứu, tham khảo, phổ cập về quyền tác giả, quyền liên quan đã được xuất bản, phát hành tới các đối tượng. Các Điều ước quốc tế, pháp luật của Việt Nam và luật pháp của một số quốc gia như Luật Bản quyền Hợp chủng quốc Hoa Kỳ, Luật Bản quyền của Liên Bang Thụy Sĩ cũng đã được dịch sang tiếng Việt để xuất bản và phát hành tới các đối tượng.</p>
        <p>Bộ niên giám đăng ký quyền tác giả được hệ thống hóa và xuất bản thường niên sau mỗi năm thực hiện việc cấp Giấy chứng nhận. Số liệu đăng ký từ 1987 đến nay được số hóa chuyển lên website quyền tác giả Việt Nam. Bộ niên giám công khai hóa dữ liệu đăng ký hàng năm, góp phần hỗ trợ công dân và các tổ chức khai thác, sử dụng tác phẩm, cuộc biểu diễn, bản ghi âm, chương trình phát sóng, đồng thời là dữ liệu để công dân có thể phát hiện các trường hợp xâm phạm quyền của tổ chức, công dân khác để nộp hồ sơ đăng ký.</p>
        <p>Bộ tranh truyện bản quyền được xuất bản lần đầu tiên với 5 tập liên quan đến việc lựa chọn nghệ nghiệp trong các lĩnh vực sáng tạo, đến quyền của người biểu diễn, quyền của nhà sản xuất bản ghi âm, quyền của tổ chức phát sóng và trong môi trường số. Với các nhân vật nhỏ tuổi được hóa thân trong “Chì tẩy”, “Latop”, “Aten” là các công cụ truyền thống và thiết bị hiện đại hỗ trợ hoạt động sáng tạo, tìm hiểu luật sở hữu trí tuệ. Dr.Tễu là nhân vật dân gian được hóa thân trong vai trò tiến sĩ, luật sư sở hữu trí tuệ, tư vấn về việc lựa chọn ngành nghề và giải đáp thắc mắc cho các em tình hiểu luật sở hữu trí tuệ. Sách được in 50 nghìn bản, với màu sắc rực rỡ, hài hòa, phát hành đến thư viện các tỉnh, thành phố phục vụ học sinh từ độ tuổi lớp 3 trở lên và những người quan tâm khác.</p>
        <p>100.000 tờ rơi đã được xuất bản để phát hành trong các trường đại học và cao đẳng với các trích dẫn Nghị quyết của Đảng và các điều luật quan trọng, nhằm phổ biến kiến thức cho sinh viên.</p>
        <p>Website quyền tác giả Việt Nam với hệ thống dữ liệu đầy đủ về luật pháp, về tổ chức quản lý và thực thi quyền tác giả, quyền liên quan của quốc gia và quốc tế, đáp ứng yêu cầu nghiên cứu, tìm hiểu của công dân Việt Nam cũng như người nước ngoài, với hai thứ tiếng gồm tiếng Việt và tiếng Anh. Các hoạt động trong nước và quốc tế về quyền tác giả, quyền liên quan được thông tin kịp thời, bằng ngôn ngữ văn tự và bằng cả âm thanh, hình ảnh.</p>
        <p>Bộ phim tư liệu về “trí tuệ Việt Nam thông điệp từ những di sản” là những tác phẩm điện ảnh giới thiệu về kiến trúc, điêu khắc cổ, về di sản vật thể và phi vật thể được bảo hộ quyền tác giả như hát sẩm, chèo truyền thống, văn hóa phồn thực, văn hóa rượu v.v… ; góp phần bảo tồn và phát triển văn học nghệ thuật dân gian được bảo hộ theo luật sở hữu trí tuệ.</p>
        <p>Hệ thống dữ liệu của Website và các thông tin cập nhật được thực hiện bởi đội ngũ cán bộ và công chức Cục Bản quyền tác giả, với sự hợp tác của các chuyên gia liên quan.</p>
        <p>Các hoạt động chỉ đạo, hướng dẫn, triển khai và kiểm tra thi hành luật pháp quốc gia và các điều ước quốc tế đã được thực hiện thường xuyên trên phạm vi toàn quốc.</p>
        <p>Các văn bản quy phạm pháp luật được phổ biến kịp thời, ngay sau khi được các cấp có thẩm quyền ký ban hành, thông qua các cuộc họp báo, đưa tin trên trang web quyền tác giả Việt Nam, in sách phát hành tới các đối tượng. Các hội nghị tập huấn triển khai thi hành được tổ chức trong phạm vi toàn quốc cho giới sáng tạo, nhà khai thác, sử dụng, các cơ quan quản lý và thực thi thuộc Trung ương và địa phương. Các hội thảo thực thi về bản quyền trong các lĩnh vực như báo chí, xuất bản, điện ảnh, mỹ thuật tạo hình, sân khấu, di sản văn hóa, quảng cáo, trong các trường đại học và cao đẳng cũng đã được tổ chức thực hiện.</p>
      </div>
    </section>
  </main>


    <%@ include file="../WebNguoiDung/CTDfooter.jsp" %>
</body>
</html>
